import Classes
Abt1 = Classes.Abteilung("abt1")
Abt2 = Classes.Abteilung("abt2")
Abt3 = Classes.Abteilung("abt3")
paul = Classes.Mitarbeiter("Paul", "Laser", 18, Classes.Geschlecht.Maennlich, Abt1)
paul2 = Classes.Mitarbeiter("Paul", "Laser", 18, Classes.Geschlecht.Maennlich, Abt2)
paul3 = Classes.Mitarbeiter("Paul", "Laser", 18, Classes.Geschlecht.Maennlich, Abt3)
paul4 = Classes.Gruppenleiter("Paul", "Laser", 18, Classes.Geschlecht.Maennlich, Abt1)
Sandra = Classes.Gruppenleiter("Sandra", "Cool", 20, Classes.Geschlecht.Weiblich, Abt2)
Sandra2 = Classes.Gruppenleiter("Sandra", "Cool", 20, Classes.Geschlecht.Weiblich, Abt3)
Sandra3 = Classes.Mitarbeiter("Sandra", "Cool", 20, Classes.Geschlecht.Weiblich, Abt2)
Sandra4 = Classes.Mitarbeiter("Sandra", "Cool", 20, Classes.Geschlecht.Weiblich, Abt2)
Sandra5 = Classes.Mitarbeiter("Sandra", "Cool", 20, Classes.Geschlecht.Weiblich, Abt2)
listepersonen = (paul, paul2, paul3, paul4, Sandra, Sandra2, Sandra3, Sandra4, Sandra5)
listeAbteilungen = (Abt1, Abt2, Abt3)
Firma = Classes.Firma(listepersonen, listeAbteilungen)
print("Mitarbeiter: " + str(Firma.countMitarbeiter()))
print("Gruppenleiter: " + str(Firma.countGruppenleiter()))
print("Abteilungen: " + str(Firma.countAbteilungen()))
frauen, maenner = Firma.percentofWomenMen()
print("%frauen: " + str(frauen) + " %männer: " + str(maenner))
print("Mitarbeiterstärkste Abteilung: " + str(Firma.strongestAbteilung()))
